baseURL = 'https://ggstuart.github.io/advanced-web-development'
theme = 'module'
title = 'Advanced Web Development'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
[languages]
    [languages.en]
        locale = "en-gb"


[markup]
    [markup.highlight]
        _merge = "shallow"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.renderHooks]
            [markup.goldmark.renderHooks.link]
                useEmbedded = "fallback"

[params]
    moduleName = 'Advanced Web development'
    moduleCode = 'CTEC3705'
    customcss = ['colours.css', 'mdn.css', 'slides.css']
